export { default as AboutSection } from './AboutSection'
export { default as ContactSection } from './ContactSection'
export { default as HomeSection } from './HomeSection'
export { default as ProjectsSection } from './ProjectsSection'
export { default as TechStackSection } from './TechStackSection'
