export const APP_NAME = 'Yan Lucas';
export const APP_DEFAULT_TITLE = 'Yan Lucas';
export const APP_TITLE_TEMPLATE = '%s | Yan Lucas';
export const APP_DESCRIPTION = 'seo_description';

export const BASE_KEYWORDS_EN = [
  'Yan',
  'Lucas',
  'Yan Lucas',
  'Yan Lucas Pereira Branco',
  'Yan Lucas software engineer',
  'Yan Lucas frontend developer',
  'Yan Lucas front-end developer',
  'Skim',
  'Credible AI',
  'Web development',
  'Software engineer',
  'Frontend',
  'FrontEnd',
  'Front-end',
  'Front end',
  'Front end developer',
  'Front-end developer',
  'FrontEnd developer',
  'React Native',
  'Mobile developer',
  'Chrome extension',
  'iOS developer',
  'Android developer',
  'Tech',
  'Programming',
  'Developer',
  'JavaScript',
  'TypeScript',
  'React',
  'Next.js',
  'Vue',
  'Angular',
  'Node.js',
  'CSS',
  'HTML',
  'Web design',
  'UI/UX',
  'GitHub',
  'Open source',
];

export const BASE_KEYWORDS_PT = [
  'Yan',
  'Lucas',
  'Yan Lucas',
  'Yan Lucas Pereira Branco',
  'Yan Lucas software engineer',
  'Yan Lucas engenheiro de software',
  'Yan Lucas frontend developer',
  'Yan Lucas front-end developer',
  'Yan Lucas desenvolvedor de frontend',
  'Yan Lucas desenvolvedor de front-end',
  'Skim',
  'Credible AI',
  'Web development',
  'Desenvolvimento web',
  'Software engineer',
  'Engenheiro de software',
  'Front-end',
  'Front end',
  'FrontEnd',
  'Frontend developer',
  'Front-end developer',
  'Front end developer',
  'FrontEnd developer',
  'Desenvolvedor de frontend',
  'Desenvolvedor de front-end',
  'Desenvolvedor front end',
  'Desenvolvedor front-end',
  'Desenvolvedor frontend',
  'React Native',
  'Desenvolvedor mobile',
  'Extensão Chrome',
  'Desenvolvedor iOS',
  'Desenvolvedor Android',
  'Tech',
  'Programming',
  'Marketing digital',
  'Developer',
  'JavaScript',
  'TypeScript',
  'React',
  'Next.js',
  'Vue',
  'Angular',
  'Node.js',
  'CSS',
  'HTML',
  'Web design',
  'UI/UX',
  'GitHub',
  'Open source',
];
