import { MetadataRoute } from 'next';

import { env } from '@env';

/**
 * Points crawlers at the sitemap. Without this the sitemap generated by
 * [src/app/sitemap.ts] is only discoverable if a crawler guesses the URL.
 *
 * `/_next/` and `/_vercel/` are build and analytics internals with no indexable
 * content; everything else, including the localized routes, is open.
 */
const robots = (): MetadataRoute.Robots => ({
  rules: [
    {
      userAgent: '*',
      allow: '/',
      disallow: ['/_next/', '/_vercel/'],
    },
  ],
  sitemap: `${env.APP_URL}/sitemap.xml`,
  host: env.APP_URL,
});

export default robots;
