interface Dict<T> {
  [key: string]: T | undefined;
}

const getSiteMetadata = <T>(env: Dict<T>) => ({
  author: 'Yan Lucas',
  title: 'Yan Lucas',
  image: '/icon.png',
  siteUrl: env.GATSBY_SITE_URL || 'https://yanlucas.com',
  social: [
    {
      name: 'github',
      url: env.GATSBY_PERSONAL_GITHUB_URL || 'https://merda.com',
    },
    {
      name: 'linkedin',
      url: env.GATSBY_PERSONAL_LINKEDIN_URL || 'https://merda.com',
    },
    {
      name: 'instagram',
      url: env.GATSBY_PERSONAL_INSTAGRAM_URL || 'https://merda.com',
    },
  ],
  br: {
    title: 'Yan Lucas - Engenheiro de Software',
    description:
      'Yan Lucas, engenheiro de software apaixonado pelo desenvolvimento de interfaces interativas e experiências digitais de alta qualidade.',
    keywords: [
      'Yan',
      'Lucas',
      'Yan Lucas',
      'Yan lucas pereira branco',
      'Yan Lucas software engineer',
      'Yan Lucas engenheiro de software',
      'Yan Lucas frontend developer',
      'Yan Lucas front-end developer',
      'Yan Lucas desenvolvedor de frontend',
      'Yan Lucas desenvolvedor de front-end',
      'Web development',
      'Desenvolvimento web',
      'Software engineer',
      'Engenheiro de software',
      'Frontent',
      'Front-end',
      'Front end',
      'FrontEnd',
      'Frontend developer',
      'Front-end developer',
      'Front end developer',
      'FrontEnd developer',
      'Desenvolvedor de frontend',
      'Desenvolvedor de front-end',
      'Desenvolvedor front end',
      'Desenvolvedor front-end',
      'Desenvolvedor frontend',
      'Desenvolvedor frontEnd',
      'Tech',
      'Programming',
      'Games',
      'Gaming',
      'Programming',
      'Digital marketing',
      'Marketing',
      'Marketing digital',
      'Marketing-digital',
      'Developer',
      'JavaScript',
      'TypeScript',
      'React',
      'Vue',
      'Angular',
      'Node.js',
      'CSS',
      'HTML',
      'Web design',
      'UI/UX',
      'GitHub',
      'Open source',
    ],
  },
  en: {
    title: 'Yan Lucas - Software Engineer',
    description:
      'Yan Lucas, software engineer passionate about developing interactive interfaces and high-quality digital experiences.',
    keywords: [
      'Yan',
      'Lucas',
      'Yan Lucas',
      'Yan lucas pereira branco',
      'Yan Lucas software engineer',
      'Yan Lucas frontend developer',
      'Yan Lucas front-end developer',
      'Web development',
      'Software engineer',
      'Frontend',
      'FrontEnd',
      'Front-end',
      'Front end',
      'Front end developer',
      'Front-end developer',
      'FrontEnd developer',
      'Tech',
      'Programming',
      'Games',
      'Gaming',
      'Digital marketing',
      'Marketing',
      'Developer',
      'JavaScript',
      'TypeScript',
      'React',
      'Vue',
      'Angular',
      'Node.js',
      'CSS',
      'HTML',
      'Web design',
      'UI/UX',
      'GitHub',
      'Open source',
    ],
  },
});

export default getSiteMetadata;
