const siteMetadata = {
  author: 'Yan Lucas',
  title: 'Yan Lucas',
  image: '/yan_icon.png',
  siteUrl: 'https://yanlucas.vercel.app/',
  description:
    'Yan Lucas, engenheiro de software apaixonado pelo desenvolvimento de interfaces interativas e experiências digitais de alta qualidade.',
  keywords: [
    'Yan',
    'Lucas',
    'Yan Lucas',
    'yan lucas pereira branco',
    'Yan Lucas software engineer',
    'Yan Lucas engenheiro de software',
    'Yan Lucas frontend developer',
    'Yan Lucas front-end developer',
    'Yan Lucas desenvolvedor de frontend',
    'Yan Lucas desenvolvedor de front-end',
    'web development',
    'desenvolvimento web',
    'software engineer',
    'engenheiro de software',
    'frontent',
    'front-end',
    'front end',
    'frontEnd',
    'frontend developer',
    'front-end developer',
    'front end developer',
    'frontEnd developer',
    'desenvolvedor de frontend',
    'desenvolvedor de front-end',
    'desenvolvedor front end',
    'desenvolvedor front-end',
    'desenvolvedor frontend',
    'desenvolvedor frontEnd',
    'tech',
    'programming',
    'games',
    'gaming',
    'programming',
    'digital marketing',
    'marketing',
    'marketing digital',
    'marketing-digital',
    'developer',
  ],
  social: [
    {
      name: 'github',
      url: 'https://github.com/zogss/',
    },
    {
      name: 'linkedin',
      url: 'https://www.linkedin.com/in/yan-lucas-54aa08216/',
    },
    {
      name: 'instagram',
      url: 'https://www.instagram.com/yan_llucasb/',
    },
  ],
}

export default siteMetadata
